"use client";

import { useState } from "react";
import api from "@/lib/api";
import type { OutreachGenerateResponse } from "@/lib/types";

interface Props {
  jobId: string;
  jobTitle?: string;
}

export default function OutreachGenerator({ jobId, jobTitle }: Props) {
  const [type, setType] = useState("cover_letter");
  const [tone, setTone] = useState("professional");
  const [resumeSummary, setResumeSummary] = useState("");
  const [result, setResult] = useState<OutreachGenerateResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    setResult(null);
    try {
      const res = await api.post<OutreachGenerateResponse>("/outreach/generate", {
        job_id: jobId,
        outreach_type: type,
        tone,
        resume_summary: resumeSummary || undefined,
      });
      setResult(res.data);
    } catch (err) {
      console.error("Failed to generate outreach", err);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (result) {
      navigator.clipboard.writeText(result.message);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="space-y-4 rounded-lg border border-gray-200 bg-white p-4">
      <h3 className="font-semibold text-gray-900">
        Generate Outreach {jobTitle && `for "${jobTitle}"`}
      </h3>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="mb-1 block text-sm font-medium text-gray-700">Type</label>
          <select
            value={type}
            onChange={(e) => setType(e.target.value)}
            className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
          >
            <option value="cover_letter">Cover Letter</option>
            <option value="recruiter_message">Recruiter Message</option>
            <option value="follow_up">Follow Up</option>
          </select>
        </div>
        <div>
          <label className="mb-1 block text-sm font-medium text-gray-700">Tone</label>
          <select
            value={tone}
            onChange={(e) => setTone(e.target.value)}
            className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
          >
            <option value="professional">Professional</option>
            <option value="casual">Casual</option>
            <option value="enthusiastic">Enthusiastic</option>
          </select>
        </div>
      </div>

      <div>
        <label className="mb-1 block text-sm font-medium text-gray-700">
          Resume Summary (optional)
        </label>
        <textarea
          value={resumeSummary}
          onChange={(e) => setResumeSummary(e.target.value)}
          placeholder="Brief summary of your experience and skills..."
          className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
          rows={3}
        />
      </div>

      <button
        onClick={handleGenerate}
        disabled={loading}
        className="w-full rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700 disabled:opacity-50"
      >
        {loading ? "Generating..." : "Generate with AI"}
      </button>

      {result && (
        <div className="space-y-2 rounded-lg border border-gray-200 bg-gray-50 p-4">
          <div className="flex items-center justify-between text-xs text-gray-500">
            <span>
              Generated by {result.provider} ({result.model}) - {result.tokens_used} tokens
            </span>
            <button
              onClick={handleCopy}
              className="rounded bg-white px-2 py-1 text-xs font-medium text-blue-600 hover:bg-blue-50"
            >
              {copied ? "Copied!" : "Copy"}
            </button>
          </div>
          <div className="whitespace-pre-wrap text-sm text-gray-800">{result.message}</div>
        </div>
      )}
    </div>
  );
}
